GET http://127.0.0.1:8000/
Accept: application/json
###

POST http://127.0.0.1:8000/api/devices/vdevo173316521541939/freeze
Content-Type: application/json
Accept: application/json
###

POST http://127.0.0.1:8000/api/devices/vdevo173316521541939/unfreeze
Content-Type: application/json
Accept: application/json
###

PUT http://127.0.0.1:8000/api/devices/vdevo173316521541939/turn-off
Content-Type: application/json
Accept: application/json
###

POST http://127.0.0.1:8000/api/devices/vdevo173316521541939/switch_off
Content-Type: application/json
Accept: application/json
###

POST http://127.0.0.1:8000/api/devices/vdevo173316521541939/switch_on
Content-Type: application/json
Accept: application/json
###

GET http://127.0.0.1:8000/devices
Accept: application/json
###

GET http://127.0.0.1:8000/rooms
Accept: application/json
###

POST http://127.0.0.1:8000/add_rooms
Content-Type: application/json
Accept: application/json

 {
     "room_id": "quarto_1",
     "devices": [
         {
             "id": "vdevo173316521541939",
             "name": "Lâmpada Inteligente",
             "category_name": "Switch",
             "category": "dj",
             "states": {}
         }
     ]
 }

###

POST http://127.0.0.1:8000/add_rooms
Content-Type: application/json
Accept: application/json

 {
     "room_id": "quarto_2",
     "devices": [
                {
             "id": "vdevo173455209899022",
             "name": "Interruptor_quarto",
             "category_name": "Switch",
             "category": "kg",
             "states": {}
         },
         {
             "id": "6836066470039f3b913c",
             "name": "Interruptor",
             "category_name": "Switch",
             "category": "kg",
                        "online": true,

             "online": true,
             "states": {}
         }
     ]
 }
###

POST http://127.0.0.1:8000/add_rooms
Content-Type: application/json
Accept: application/json

 {
     "room_id": "quarto_2",
     "devices": [
         {
             "id": "6836066470039f3b913c",
             "name": "Interruptor",
             "category_name": "Switch",
             "category": "kg",
             "states": {}
         },
            {
                "id": "vdevo173316521541939",
                "name": "Lâmpada Inteligente",
                "category_name": "Switch",
                "category": "dj",
                "states": {}
            }
     ]
 }
###

POST http://127.0.0.1:8000/api/devices/vdevo173455209899022/DoNotDisturbActivate
Content-Type: application/json
Accept: application/json
###

POST http://127.0.0.1:8000/api/devices/vdevo173455209899022/DoNotDisturbDeactivate
Content-Type: application/json
Accept: application/json
###

POST http://127.0.0.1:8000/api/devices/vdevo173455209899022/CleaningActivate
Content-Type: application/json
Accept: application/json
###

POST http://127.0.0.1:8000/api/devices/vdevo173455209899022/CleaningDeactivate
Content-Type: application/json
Accept: application/json
###

POST http://127.0.0.1:8000/api/devices/vdevo173455209899022/BellActivate
Content-Type: application/json
Accept: application/json
###

POST http://127.0.0.1:8000/api/devices/vdevo173455209899022/BellDeactivate
Content-Type: application/json
Accept: application/json
###

DELETE http://127.0.0.1:8000/delete_room/
Content-Type: application/json
Accept: application/json
###

POST http://127.0.0.1:8000/add_rooms
Content-Type: application/json
Accept: application/json

{
  "room_id": "300",
  "devices": [
    {
      "id": "vdevo173455209899022",
      "name": "NH-YM 蓝牙mesh 2L 单零火-vdevo",
      "category_name": "Switch",
      "category": "kg",
      "states": {
        "switch_1": "ON",
        "switch_2": "OFF",
        "switch_3": "OFF"
      }
    },
    {
      "id": "vdevo173316521541939",
      "name": "Lâmpada Inteligente",
      "category_name": "Light Source",
      "category": "dj",
      "states": {
        "switch_led": "ON"
      }
    },
    {
      "id": "6836066470039f3b913c",
      "name": "Interruptor",
      "category_name": "Switch",
      "category": "kg",
      "states": {
        "switch_1": "OFF",
        "switch_2": "OFF",
        "switch_3": "OFF"
      }
    }
  ]
}

###
POST http://127.0.0.1:8000/add_rooms
Content-Type: application/json
Accept: application/json

{
  "room_id": "301",
  "devices": [
    {
      "id": "vdevo173455209899022",
      "name": "NH-YM 蓝牙mesh 2L 单零火-vdevo",
      "category_name": "Switch",
      "category": "kg",
      "states": {
        "switch_1": "OFF",
        "switch_2": "ON",
        "switch_3": "OFF"
      }
    },
    {
      "id": "vdevo173316521541939",
      "name": "Lâmpada Inteligente",
      "category_name": "Light Source",
      "category": "dj",
      "states": {
        "switch_led": "ON"
      }
    },
    {
      "id": "6836066470039f3b913c",
      "name": "Interruptor",
      "category_name": "Switch",
      "category": "kg",
      "states": {
        "switch_1": "OFF",
        "switch_2": "OFF",
        "switch_3": "OFF"
      }
    }
  ]
}

###
POST http://127.0.0.1:8000/add_rooms
Content-Type: application/json
Accept: application/json

{
  "room_id": "302",
  "devices": [
    {
      "id": "vdevo173455209899022",
      "name": "NH-YM 蓝牙mesh 2L 单零火-vdevo",
      "category_name": "Switch",
      "category": "kg",
      "states": {
        "switch_1": "OFF",
        "switch_2": "OFF",
        "switch_3": "ON"
      }
    },
    {
      "id": "vdevo173316521541939",
      "name": "Lâmpada Inteligente",
      "category_name": "Light Source",
      "category": "dj",
      "states": {
        "switch_led": "ON"
      }
    },
    {
      "id": "6836066470039f3b913c",
      "name": "Interruptor",
      "category_name": "Switch",
      "category": "kg",
      "states": {
        "switch_1": "OFF",
        "switch_2": "OFF",
        "switch_3": "OFF"
      }
    }
  ]
}

